Feature/4-2
ryota-09/ex-vue-emp-manage-bugfix pull request #6
Opened 2022-02-21 06:22 UTC by ryota-09

src/views/employeeList.vue
templateタグ内の給料部分を修正しました。

2022-02-21 06:47 UTC, igamasayuki requested changes
気になる点をコメントしました。
差し戻しますので、再度pushして管理シートより再レビュー依頼をしてください。
(この場合、push後、再度プルリクを作る必要はありません。)

2022-02-21 06:47 UTC, igamasayuki commented on src/views/EmployeeDetail.vue
> +              <td>{{ currentEmployee.salary.toLocaleString() }}円</td>
Employeeクラスにフォーマットして返すGetterを１つ用意して呼ぶと汎用性が高まります。
4-1と同様です。

2022-02-21 07:38 UTC, ryota-09 commented on src/views/EmployeeDetail.vue
> +              <td>{{ currentEmployee.salary.toLocaleString() }}円</td>
employeeクラスにフォーマットするgetterを組み込みました。

2022-02-21 07:43 UTC, igamasayuki requested changes
気になる点をコメントしました。
差し戻しますので、再度pushして管理シートより再レビュー依頼をしてください。
(この場合、push後、再度プルリクを作る必要はありません。)

2022-02-21 07:43 UTC, igamasayuki commented on src/store/index.ts
> +            employee.salaryStringPretty(employee.salary),
EmployeeクラスのsalaryStringPretty()はGetterなので引数入れたこの呼び出しはエラーになりませんか？

ここは修正の必要はありませんので戻すようにお願いします。

2022-02-21 08:34 UTC, ryota-09 commented on src/views/EmployeeDetail.vue
> +              <td>{{ currentEmployee.salary.toLocaleString() }}円</td>
employeeクラスにgetterとして組み込みました。

2022-02-21 08:47 UTC, igamasayuki requested changes
気になる点をコメントしました。
差し戻しますので、再度pushして管理シートより再レビュー依頼をしてください。
(この場合、push後、再度プルリクを作る必要はありません。)

2022-02-21 08:47 UTC, igamasayuki commented on src/store/index.ts
> +            employee.salaryStringPretty(employee.salary),
ここは
employee.salary,
のままで大丈夫です。

2022-02-21 08:47 UTC, igamasayuki commented on src/types/employee.ts
> +  get salaryStringPretty(): string{
TSDocコメントを記載しましょう。

2022-02-21 08:47 UTC, igamasayuki commented on src/views/EmployeeDetail.vue
> +              <td>{{ currentEmployee.salary }}円</td>
ここで
salaryStringPrettyという名前のGetterを呼ぶイメージです。

2022-02-22 02:01 UTC, igamasayuki approved these changes
とてもわかりやすくなったと思います。

気になる点をコメントしました。
承認しますが、必要であれば後ほど修正をしておきましょう。

2022-02-22 02:01 UTC, igamasayuki commented on src/types/employee.ts
> +
TSDocコメントを記載しましょう。

2022-02-22 02:01 UTC, merged